---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/matches":
    get:
      summary: List matches
      tags:
      - Matches
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      matches:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            player1_id:
                              type: integer
                            player2_id:
                              type: integer
                            start_time:
                              type: string
                              format: date-time
                            end_time:
                              type: string
                              format: date-time
                            winner_id:
                              type: integer
                              nullable: true
                            table_number:
                              type: integer
                          required:
                          - id
                          - player1_id
                          - player2_id
                          - start_time
                          - table_number
                    required:
                    - matches
    post:
      summary: Create match
      tags:
      - Matches
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      match:
                        type: object
                        properties:
                          id:
                            type: integer
                          player1_id:
                            type: integer
                          player2_id:
                            type: integer
                          start_time:
                            type: string
                            format: date-time
                          end_time:
                            type: string
                            format: date-time
                          winner_id:
                            type: integer
                            nullable: true
                          table_number:
                            type: integer
                        required:
                        - id
                        - player1_id
                        - player2_id
                        - start_time
                        - table_number
                    required:
                    - matches
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                player1_id:
                  type: integer
                player2_id:
                  type: integer
                start_time:
                  type: string
                  format: date-time
                end_time:
                  type: string
                  format: date-time
                winner_id:
                  type: integer
                  nullable: true
                table_number:
                  type: integer
              required:
              - player1_id
              - player2_id
              - start_time
              - table_number
  "/api/v1/matches/{id}":
    parameters:
    - name: id
      in: path
      description: Match ID
      required: true
      schema:
        type: integer
    get:
      summary: Show match
      tags:
      - Matches
      responses:
        '200':
          description: successful
        '404':
          description: not found
    put:
      summary: Update match
      tags:
      - Matches
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                player1_id:
                  type: integer
                player2_id:
                  type: integer
                start_time:
                  type: string
                  format: date-time
                end_time:
                  type: string
                  format: date-time
                winner_id:
                  type: integer
                  nullable: true
                table_number:
                  type: integer
    delete:
      summary: Delete match
      tags:
      - Matches
      responses:
        '204':
          description: no content
        '404':
          description: not found
  "/api/v1/players":
    get:
      summary: List players
      tags:
      - Players
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      players:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                            ranking:
                              type: integer
                            profile_picture_url:
                              type: string
                            preferred_cue:
                              type: string
                          required:
                          - id
                          - name
                          - profile_picture_url
                    required:
                    - players
    post:
      summary: Create player
      tags:
      - Players
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      player:
                        type: object
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
                          ranking:
                            type: integer
                          profile_picture_url:
                            type: string
                          preferred_cue:
                            type: string
                        required:
                        - id
                        - name
                        - profile_picture_url
                      presigned_url:
                        type: string
                    required:
                    - players
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                ranking:
                  type: integer
                profile_picture_url:
                  type: string
                preferred_cue:
                  type: string
              required:
              - name
              - profile_picture_url
  "/api/v1/players/{id}":
    parameters:
    - name: id
      in: path
      description: Player ID
      required: true
      schema:
        type: integer
    get:
      summary: Show player
      tags:
      - Players
      responses:
        '200':
          description: successful
        '404':
          description: not found
    put:
      summary: Update player
      tags:
      - Players
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                ranking:
                  type: integer
                profile_picture_url:
                  type: string
                preferred_cue:
                  type: string
    delete:
      summary: Delete player
      tags:
      - Players
      responses:
        '204':
          description: no content
        '404':
          description: not found
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
